# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  schedule:
    - cron: "0 0 12 * 10 ?" #10월 한달동안 12시에
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      EVERY_TIME_ID: ${{secrets.EVERY_TIME_ID}}
      EVERY_TIME_PASSWORD: ${{secrets.EVERY_TIME_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Google Chrome
        run: |
          chmod +x installChrome.sh
          ./installChrome.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: export DISPLAY=:0.0
      - name: Build with Gradle
        run: ./gradlew run
